croc_blanc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('crud.urls')),
]

crud/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    #VETO
	url(r'^veto/create/$', views.createVeterinaire, name='veto-create'),
	url(r'^veto/update/(?P<id>[0-9]+)/$', views.updateVeterinaire, name='veto-update'),
	url(r'^veto/delete/(?P<id>[0-9]+)/$', views.deleteVeterinaire, name='veto-delete'),
	url(r'^veto/display/$', views.displayVeterinaire, name='veto-display'),
	url(r'^veto/display/(?P<id>[0-9]+)/$', views.displayVeterinaire, name='veto-display'),
    #CHAT
    url(r'^chat/create/$', views.createChat, name='chat-create'),
    url(r'^chat/display/adopte$', views.displayChatAdopteAction, name='chat-display-adopte'),
    url(r'^chat/display/fa$', views.displayChat, name='chat-display-fa'),
    url(r'^chat/delete/(?P<id>[0-9]+)/$', views.deleteChat, name='chat-delete'),
    url(r'^chat/display/(?P<id>[0-9]+)/$', views.displayChat, name='chat-display'),
    url(r'^chat/update/(?P<id>[0-9]+)/$', views.updateChat, name='chat-update'),
    url(r'^chat/adopte/(?P<id>[0-9]+)/$', views.adopteChat, name='chat-adopte'),
    #CONNECTION
    url(r'^connection/', views.connect, name='connect'),
	url(r'^disconnect/', views.disconnect, name='disconnect'),
    #EMAIL
    url(r'^chat/email', views.email, name='email'),
]

crud/models.py
#-*- coding: utf-8 -*-
from django.db import models

class User(models.Model):
    id_user = models.AutoField(primary_key=True)
    email = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)

class Chat(models.Model):
    id_chat         = models.AutoField(primary_key=True)
    prenom          = models.CharField(max_length=50)
    sexe            = models.BooleanField()
    date_naissance  = models.DateField()
    entree_le       = models.DateField()
    identification  = models.IntegerField()
    sterilise       = models.BooleanField()
    date_steri      = models.DateField(blank=True, null=True)
    test_vih        = models.IntegerField()
    date_test_vih   = models.DateField(blank=True, null=True)
    adopte          = models.BooleanField()
    nom_fa          = models.CharField(max_length=50, blank=True, null=True)
    nom_adoptant    = models.CharField(max_length=50, blank=True, null=True)
    commentaire     = models.TextField(blank=True, null=True)
    n_puce          = models.CharField(max_length=100, blank=True, null=True)
    n_tatouage      = models.CharField(max_length=100, blank=True, null=True)

class Veterinaire(models.Model):
    id_vet = models.AutoField(primary_key=True)
    nom_vet = models.CharField(max_length=50)
    address_1 = models.CharField(max_length=255, blank=True, null=True)
    address_2 = models.CharField(max_length=255, blank=True, null=True)
    ville = models.CharField(max_length=50, blank=True, null=True)
    numero_tel = models.CharField(max_length=10, blank=True, null=True)

#Abstract class for all the actions possible on a cat
class Action(models.Model):
    id_action = models.AutoField(primary_key=True)
    date_action = models.DateField()
    veterinaire = models.ForeignKey(Veterinaire)
    chat = models.ForeignKey(Chat)

class Vaccin(Action):
    type_vaccin = models.IntegerField()

class Soin(Action):
    description = models.TextField()
    num_soin = models.IntegerField()

crud/forms.py
from django import forms
from django.forms import ModelForm
from crud.models import Chat, Action, Vaccin, Soin, Veterinaire

IDENTIFICATION = [(1, 'Pas encore faite'), (2, 'Puce'), (3, 'Tatouage'),]
VIH = [(0, 'Pas encore fait'), (1, 'Positif'), (2, 'Négatif'),]
SEXE = [(True, 'Male'), (False, 'Femelle'),]

class createVeterinaireForm(ModelForm):
    class Meta:
        model = Veterinaire
        exclude = ['id_vet']

class createChatForm(ModelForm):
    identification = forms.ChoiceField(required=True, choices=IDENTIFICATION)
    test_vih = forms.ChoiceField(required=True, choices=VIH)
    sexe = forms.ChoiceField(required=True, choices=SEXE)
    date_naissance = forms.CharField(required=True)
    entree_le = forms.CharField(required=True)
    number = forms.CharField(required=False)
    date_steri = forms.CharField(required=False)
    date_test_vih = forms.CharField(required=False)
    class Meta:
        model = Chat
        exclude = ['id_chat', 'identification', 'test_vih', 'sexe', 'date_naissance', 'entree_le', \
                   'n_puce', 'n_tatouage', 'date_test_vih', 'date_steri']

crud/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse
from crud.impl.veterinaire import *
from crud.impl.chat import *
from crud.models import User, Chat, Action, Vaccin, Soin, Veterinaire
from django.core.mail import send_mail
from datetime import timedelta, date as datef
import logging
import datetime
from urllib.parse import urlencode

logger = logging.getLogger('croc_blanc.log')

# Show log of actions
def printInfoLog(message, request):
    idUser = 'none'
    if 'id_user' in request.session:
        idUser = request.session['id_user'].__str__()
    dayDate = datetime.datetime.now()
    logger.info(dayDate.__str__() + '|' +  idUser + '|' + message + "|" + request.method.__str__() + "|" \
                + request.path + "|" + urlencode(request.POST) + "|" + urlencode(request.GET) + ">")

# Util function used to check if the user is authenticated or not
def isAuthenticated(request):
    if 'connected' in request.session:
        if request.session['connected'] == True:
            return True
    return False


# Create your views here.

def connect(request):
    printInfoLog("Login attempt",request)
    if request.method == 'POST':
        try:
            user = User.objects.get(email=request.POST['login'])
            if user.password == request.POST['password']:
                printInfoLog("Login successful", request)
                request.session['connected'] = True
                request.session['id_user'] = user.id_user
                return displayChat(request)
            else:
                request.session['connected'] = False
                request.session['id_user'] = 0
                return render(request, 'login.html')
        except (User.DoesNotExist):
            request.session['connected'] = False
            request.session['id_user'] = 0
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')


def disconnect(request):
    if 'connected' in request.session:
        del request.session['connected']
    return connect(request)


def index(request):
    printInfoLog("Index", request)
    if isAuthenticated(request):
        return render(request, 'index.html')
    else:
        return redirect('/connection')


def updateVeterinaire(request, id):
    printInfoLog("Update Veterinaire", request)
    if isAuthenticated(request):
        return updateVeterinaireAction(request, id)
    else:
        return redirect('/connection')


def deleteVeterinaire(request, id):
    printInfoLog("Delete Veterinaire", request)
    if isAuthenticated(request):
        return deleteVeterinaireAction(request, id)
    else:
        return redirect('/connection')


def displayVeterinaire(request, id=-1):
    printInfoLog("Display veterinaire: " + id.__str__(), request)
    if isAuthenticated(request):
        return displayVeterinaireAction(request, id)
    else:
        return redirect('/connection')


def createVeterinaire(request):
    printInfoLog("Create Veterinaire", request)
    if isAuthenticated(request):
        return createVeterinaireAction(request)
    else:
        return redirect('/connection')


def createChat(request):
    printInfoLog("Create Chat", request)
    if isAuthenticated(request):
        return createChatAction(request)
    else:
        return redirect('/connection')


def displayChat(request, id=-1):
    printInfoLog("Display Chat", request)
    if isAuthenticated(request):
        return displayChatAction(request, id)
    else:
        return redirect('/connection')


def updateChat(request, id):
    printInfoLog("Update Chat", request)
    if isAuthenticated(request):
        return updateChatAction(request, id)
    else:
        return redirect('/connection')


def deleteChat(request, id):
    printInfoLog("Delete Chat", request)
    if isAuthenticated(request):
        return deleteChatAction(request, id)
    else:
        return redirect('/connection')


def adopteChat(request, id):
    printInfoLog("Adopte Chat", request)
    if isAuthenticated(request):
        return adopteChatAction(request, id)
    return redirect('/connection')


def email(request):
    chats = Chat.objects.all().filter(adopte=False)
    primoChat = []
    rappelChat = []
    premierRappelChat = []
    steriChat = []
    for chat in chats:
        vaccin = Vaccin.objects.filter(chat=chat).annotate(max_date=Max('date_action'))
        if len(vaccin) > 0:
            # If only one vaccine was done
            if len(vaccin)==1 and vaccin[0].type_vaccin == 0:
                date = timedelta(days=21)
                if vaccin[0].date_action + date < datetime.datetime.now().date():
                    premierRappelChat.append(chat)
            # If more than one vaccin was done
            if vaccin[len(vaccin)-1].type_vaccin > 0:
                date = timedelta(days=330)
                if vaccin[0].date_action + date < datetime.datetime.now().date():
                    rappelChat.append(chat)
        else:
            # If the cat wasn't vaccinated
            date = timedelta(days=15)
            if chat.entree_le + date < datetime.datetime.now().date():
                primoChat.append(chat)
        # If the cat is 6 month old we need to sterilize it
        date = timedelta(days=180)
        if chat.sterilise == False and chat.date_naissance + date < datetime.datetime.now().date():
            steriChat.append(chat)

    textMessage = render_to_string('email.html', {
        'chatPrimo': primoChat,
        'chatPremierRappel': premierRappelChat,
        'chatRappel': rappelChat,
        'chatCastration': steriChat
    })

    today = datef.today()

    send_mail(
        'Croc blanc - ' + today.day.__str__() + '/' + today.month.__str__() + '/' + today.year.__str__(),
        textMessage,
        'no-reply@croc-blanc.fr',
        ['***REMOVED***'],
        fail_silently=False,
        auth_user=None,
        auth_password=None,
        connection=None,
        html_message=textMessage
    )
    return HttpResponse("OK")

crud/templates/chat/create.html
{% extends 'header.html' %}

{% block page_name %}
Création d'un nouveau chat
{% endblock %}

{% block content %}
    <form id="chat_form" action="{% url "chat-create" %}" method="post">
    {% csrf_token %}
    <div class="mui-row">
        <div class="mui-col-md-6">
            <h2>Identification du chat</h2>
            <div class="mui-textfield">
                {{ form.prenom }}
                <label>Prenom du chat :</label>
            </div>
            <div class="mui-select">
                {{ form.identification }}
                <label>Méthode d'identification</label>
            </div>
            <div class="mui-textfield" id="auth_number">
                {{ form.number }}
                <label>Numéro d'identification :</label>
            </div>
            <div class="mui-select">
                {{ form.sexe }}
            </div>
            <div class="mui-checkbox">
                {{ form.sterilise }}
                <label>Sterilisation ?</label>
            </div>
            <div class="mui-textfield" id="date_steri">
                {{ form.date_steri }}
                <label>Date de la stérilisation</label>
            </div>
            <div class="mui-select">
                {{ form.test_vih }}
                <label>Test VIH</label>
            </div>
             <div class="mui-textfield" id="date_test_vih">
                {{ form.date_test_vih }}
                <label>Date du test vih</label>
            </div>
            <div class="mui-textfield mui-textfield--float-left">
                {{ form.date_naissance }}
                <label>Date de naissance :</label>
            </div>
        </div>
        <div class="mui-col-md-6">
            <h2>Info croc blanc</h2>
            <div class="mui-textfield">
                {{ form.nom_fa }}
                <label>Info FA</label>
            </div>
            <div class="mui-textfield mui-textfield--float-left">
                {{ form.entree_le }}
                <label>Date de recueil par l'association</label>
            </div>
            <div class="mui-checkbox">
                {{ form.adopte }}
                <label>Adopté ?</label>
            </div>
            <div class="mui-textfield">
                {{ form.nom_adoptant }}
                <label>Nom adoptant</label>
            </div>
            <div class="mui-textfield">
            <textarea rows="5" class="mui--is-dirty mui--is-empty"
                      cols="40" id="id_commentaire" name="commentaire"></textarea>
                <label>Commentaires</label>
            </div>
        </div>
    </div>
    <div class="mui-col-md-6">
        <div class="mui-panel">
            <h1>Vaccins</h1>
            <div class="row" id="vaccin_-1"></div>
            <!-- Qd on clique ici, ajouter 3ème rappel, 4ème… -->
            <button type="button" id="add_vaccin" class="btn btn-secondary">Ajouter un vaccin</button>
        </div>
    </div>
    <div class="mui-col-md-6">
        <div class="mui-panel">
            <h1>Soins</h1>
            <div class="row" id="soin_-1"></div>
            <!-- Qd on clique ici, ajouter 3ème rappel, 4ème… -->
            <button type="button" id="add_soin" class="btn btn-secondary">Ajouter un soin</button>
        </div>
    </div>


        <button class="btn waves-effect waves-light submit-button" type="submit" name="action">Insérer
    </button>
</form>
<script>
    var options = "" {% for vet in veto  %} + '<option value="{{ vet.id_vet }}">{{ vet.nom_vet }}</option>'{% endfor %};
    var i = 0;
    var k = 0;
    $('#add_vaccin').click(function() {
        var html = '';
        html += '<div class="row" id="vaccin_'+ i +'">';
        html += (i == 0) ? "<p>Primo vaccination :</p>":"<p>Rappel n°"+ (i+1) +" :</p>";
        html += '<div class="col-sm-6">';
        html += '<div class="form-group">';
        html += '<p>Date: ';
        html += '<input type="text" name="date_vaccin_' + i + '" id="date_vaccin_' + i + '" required>';
        html += '<select class="custom-select" name="vaccin_veto_name_' + i + '">' + options + '</select>';
        html += '<input type="button" id="del_vaccin_' + i + '" value="Annuler le rappel"/>';
        html += '</p>';
        html += '</div>';
        html += '</div>';
        html += '</div>';

        var j = i - 1;
        if( j >= 0){
          $('#del_vaccin_' + j).prop("disabled",true);
        }

        $('#vaccin_'+j).after(html);
        $(function() {$('#date_vaccin_' + i).datepicker({dateFormat: 'dd/mm/yy'});});
        $('#vaccin_' + i).on('click','#del_vaccin_' + i,function() {
            $(this).closest("div.row").remove();
            i--;
        });
        i++;
    });
    $('#add_soin').click(function() {
        var html = '';
        html += '<div class="row" id="soin_' + k + '">';
        html += 'Soin n°' + (k+1) + ':';
        html += '<div class="col-sm-6">';
        html += '<div class="form-group">';
        html += '<p>Date:';
        html += '<input type="text" name="date_soin_' + k + '"';
        html += 'id="date_soin_' + k + '" required />';
        html += '<select class="custom-select" name="soin_veto_name_' + k + '">' + options + '</select>';
        html += '<input type="text" placeholder="Description du soin" name="desc_soin_' + k + '"';
        html += 'id="desc_soin_' + k + '" />';
        html += '<input type="button" id="del_soin_' + k + '" value="Annuler le soin"/>';
        html += '</p>';
        html += '</div>';
        html += '</div>';
        html += '</div>';

        var j = k - 1;
        if( j >= 0){
            $('#del_soin_' + j).prop("disabled",true);
        }
        $('#soin_'+j).after(html);
        $(function() {$('#date_soin_' + k).datepicker({dateFormat: 'dd/mm/yy'});});
        $('#soin_' + k).on('click','#del_soin_' + k,function() {
            $(this).closest("div.row").remove();
            k--;
        });
        k++;
    });
    $(function() {
        $( "#id_sterilise").click(function() {
            if ($(this).is(':checked')) {
                $("#date_steri").show();
                $("#id_date_steri").prop('required', true);
            } else {
                $("#date_steri").hide();
                $("#id_date_steri").prop('required', false);
            }
        });
        $( "#id_test_vih").change(function() {
            if ($(this).find('option:selected').val() != 0) {
                $("#date_test_vih").show();
                $("#id_date_test_vih").prop('required', true);
            } else {
                $("#date_test_vih").hide();
                $("#id_date_test_vih").prop('required', false);
            }
        });
    });
    $(function() {
        $( "#id_date_naissance" ).datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $( "#id_entree_le" ).datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $( "#id_date_steri" ).datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $( "#id_date_test_vih" ).datepicker({dateFormat: 'dd/mm/yy'});
    });

    $("#id_identification").change(function(){
        if ($(this).find('option:selected').val() != 1) {
            $("#auth_number").show();
            $("#id_number").prop('required', true);
        } else {
            $("#auth_number").hide();
            $("#id_number").prop('required', false);
        }
    });

    if($("#id_identification").find('option:selected').val() == 1) {
        $("#auth_number").hide();
        $("#id_number").prop('required', false);
    }  else {
        $("#id_number").prop('required', true);
    }

</script>
{% endblock %}

crud/templates/chat/edit.html
{% extends 'header.html' %}

{% block page_name %}
Edition d'un chat
{% endblock %}

{% block content %}
<form id="chat_form" action="{% url 'index' %}chat/update/{{id}}/" method="post">
    {% csrf_token %}
    <div class="mui-row">
        <div class="mui-col-md-6">
            <h2>Identification du chat</h2>
            <div class="mui-textfield">
                {{ form.prenom }}
                <label>Prenom du chat :</label>
            </div>
            <div class="mui-select">
                {{ form.identification }}
                <label>Méthode d'identification</label>
            </div>
            <div class="mui-textfield" id="auth_number">
                {{ form.number }}
                <label>Numéro d'identification :</label>
            </div>
            <div class="mui-select">
                {{ form.sexe }}
            </div>
            <div class="mui-checkbox">
                {{ form.sterilise }}
                <label>Sterilisation ?</label>
            </div>
            <div class="mui-textfield" id="date_steri">
                {{ form.date_steri }}
                <label>Date de la stérilisation</label>
            </div>
            <div class="mui-select">
                {{ form.test_vih }}
                <label>Test VIH</label>
            </div>
            <div class="mui-textfield" id="date_test_vih">
                {{ form.date_test_vih }}
                <label>Date du test vih</label>
            </div>
            <div class="mui-textfield mui-textfield--float-left">
                {{ form.date_naissance }}
                <label>Date de naissance :</label>
            </div>
        </div>
        <div class="mui-col-md-6">
            <h2>Info croc blanc</h2>
            <div class="mui-textfield">
                {{ form.nom_fa }}
                <label>Info FA</label>
            </div>
            <div class="mui-textfield mui-textfield--float-left">
                {{ form.entree_le }}
                <label>Date de recueil par l'association</label>
            </div>
            <div class="mui-checkbox">
                {{ form.adopte }}
                <label>Adopté ?</label>
            </div>
            <div class="mui-textfield">
                {{ form.nom_adoptant }}
                <label>Nom adoptant</label>
            </div>
            <div class="mui-textfield">
                <textarea rows="5" class="mui--is-dirty mui--is-empty"
                          cols="40" id="id_commentaire" name="commentaire"></textarea>
                <label>Commentaires</label>
            </div>
        </div>
    </div>
    <div class="mui-col-md-6">
        <div class="mui-panel">
        <h1>Vaccins</h1>
        <div class="row" id="vaccin_-1"></div>
        {% for vaccin in vaccins %}
            <div class="row" id="vaccin_{{ vaccin.type_vaccin }}">
                <input type="text" name="vaccin_{{ vaccin.type_vaccin }}" value="1" hidden/>
                {% if vaccin.type_vaccin == 0 %}
                    <p>Primo vaccination</p>
                {% else %}
                    <p>Rappel n°{{ vaccin.type_vaccin }}</p>
                {% endif %}
                <div class="col-sm-6">
                    <div class="form-group">
                        <p>Date:
                            <input type="text" name="date_vaccin_{{ vaccin.type_vaccin }}"
                               id="date_vaccin_{{ vaccin.type_vaccin }}"
                               required value="{{ vaccin.date_action }}"/>
                            <select disabled><option value="{{ vaccin.veterinaire.id_vet }}">{{ vaccin.veterinaire.nom_vet }}</option></select>
                        <script>
                            $(function () {
                                $('#date_rappel{{vaccin.type_vaccin}}').datepicker({dateFormat: 'dd/mm/yy'});
                            });
                        </script>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- Qd on clique ici, ajouter 3ème rappel, 4ème… -->
        <button type="button" id="add_vaccin" class="btn btn-secondary">Ajouter un rappel</button>
        </div>
    </div>
    <div class="mui-col-md-6">
        <div class="mui-panel">
        <h1>Soins</h1>
        <div class="row" id="soin_-1"></div>
        {% for soin in soins %}
            <div class="row" id="soin_{{ soin.num_soin }}">
                <input type="text" name="soin_{{ soin.num_soin }}" value="1" hidden/>
                Soin n°{{ soin.num_soin | add:"1"}}:
                <div class='col-sm-6'>
                    <div class="form-group">
                        <p>Date:
                            <input type="text" name="date_soin_{{ soin.num_soin }}"
                                   id="date_soin_{{ soin.num_soin }}"
                                   required value="{{ soin.date_action }}"/>
                            <script>
                                $(function () {
                                    $('#date_soin_{{soin.num_soin}}').datepicker({dateFormat: 'dd/mm/yy'});
                                });
                            </script>
                            <select disabled><option value="{{ soin.veterinaire.id_vet }}">{{ soin.veterinaire.nom_vet }}</option></select>
                            <input type="text" placeholder="Description du soin" name="desc_soin_{{ soin.num_soin }}"
                                   id="desc_soin_{{ soin.num_soin }}" value="{{ soin.description }}" />
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- Qd on clique ici, ajouter 3ème rappel, 4ème… -->
        <button type="button" id="add_soin" class="btn btn-secondary">Ajouter un soin</button>
        </div>
    </div>

    <button class="btn waves-effect waves-light submit-button" type="submit" name="action">Sauvegarder</button>
</form>
<script>
    var i = {% if vaccins|length > 0 %}{{vaccins.last.type_vaccin | add:"1"}}{% else %}0{% endif %};
    var options = "" {% for vet in veto  %} + '<option value="{{ vet.id_vet }}">{{ vet.nom_vet }}</option>'{% endfor %};
    var k = {% if soins|length > 0 %}{{soins.last.num_soin | add:"1"}}{% else %}0{% endif %};

    $('#add_vaccin').click(function() {
        var html = '';
        html += '<div class="row" id="vaccin_'+ i +'">';
        html += (i == 0) ? "<p>Primo vaccination :</p>":"<p>Rappel n°"+ i +" :</p>";
        html += '<div class="col-sm-6">';
        html += '<div class="form-group">';
        html += '<p>Date: ';
        html += '<input type="text" name="date_vaccin_' + i + '" id="date_vaccin_' + i + '" required>';
        html += '<select class="custom-select" name="vaccin_veto_name_' + i + '">' + options + '</select>';
        html += '<input type="button" id="del_vaccin_' + i + '" value="Annuler le rappel"/>';
        html += '</p>';
        html += '</div>';
        html += '</div>';
        html += '</div>';

        var j = i - 1;
        if( j >= 0){
          $('#del_vaccin_' + j).prop("disabled",true);
        }

        $('#vaccin_'+j).after(html);
        $(function() {$('#date_vaccin_' + i).datepicker({dateFormat: 'dd/mm/yy'});});
        $('#vaccin_' + i).on('click','#del_vaccin_' + i,function() {
            $(this).closest("div.row").remove();
            i--;
        });
        i++;
    });
    $('#add_soin').click(function() {
        var html = '';
        html += '<div class="row" id="soin_' + k + '">';
        html += 'Soin n°' + (k+1) + ':';
        html += '<div class="col-sm-6">';
        html += '<div class="form-group">';
        html += '<p>Date:';
        html += '<input type="text" name="date_soin_' + k + '"';
        html += 'id="date_soin_' + k + '" required />';
        html += '<select class="custom-select" name="soin_veto_name_' + k + '">' + options + '</select>';
        html += '<input type="text" placeholder="Description du soin" name="desc_soin_' + k + '"';
        html += 'id="desc_soin_' + k + '" />';
        html += '<input type="button" id="del_soin_' + k + '" value="Annuler le soin"/>';
        html += '</p>';
        html += '</div>';
        html += '</div>';
        html += '</div>';

        var j = k - 1;
        if( j >= 0){
            $('#del_soin_' + j).prop("disabled",true);
        }
        $('#soin_'+j).after(html);
        $(function() {$('#date_soin_' + k).datepicker({dateFormat: 'dd/mm/yy'});});
        $('#soin_' + k).on('click','#del_soin_' + k,function() {
            $(this).closest("div.row").remove();
            k--;
        });
        k++;
    });
    $(function() {
        $( "#id_sterilise").click(function() {
            if ($(this).is(':checked')) {
                $("#date_steri").show();
                $("#id_date_steri").prop('required', true);
            } else {
                $("#date_steri").hide();
                $("#id_date_steri").prop('required', false);
            }
        });
        $( "#id_test_vih").change(function() {
            if ($(this).find('option:selected').val() != 0) {
                $("#date_test_vih").show();
                $("#id_date_test_vih").prop('required', true);
            } else {
                $("#date_test_vih").hide();
                $("#id_date_test_vih").prop('required', false);
            }
        });
    });
    $(function() {
        $( "#id_date_naissance" ).datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $( "#id_entree_le" ).datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $( "#id_date_steri" ).datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $( "#id_date_test_vih" ).datepicker({dateFormat: 'dd/mm/yy'});
    });

    /* Display the fields if vih and castration are done */
    if ($("#id_sterilise").is(':checked')) {
        $("#date_steri").show();
        $("#id_date_steri").prop('required', true);
    } else {
        $("#date_steri").hide();
        $("#id_date_steri").prop('required', false);
    }
    if ($("#id_test_vih").find('option:selected').val() != 0) {
        $("#date_test_vih").show();
        $("#id_date_test_vih").prop('required', true);
    } else {
        $("#date_test_vih").hide();
        $("#id_date_test_vih").prop('required', false);
    }

    $("#id_identification").change(function(){
        if ($(this).find('option:selected').val() != 1) {
            $("#auth_number").show();
            $("#id_number").prop('required', true);
        } else {
            $("#auth_number").hide();
            $("#id_number").prop('required', false);
        }
    });

    if($("#id_identification").find('option:selected').val() == 1) {
        $("#auth_number").hide();
        $("#id_number").prop('required', false);
    } else {
        $("#id_number").prop('required', true);
    }

</script>
{% endblock %}